spring:
  application:
    name: Api-GateWay

  
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/order_service/**
        

server:
  port: 8885
